// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaServitec.Data;

#nullable disable

namespace SistemaServitec.Migrations
{
    [DbContext(typeof(SistemaServitecDBContex))]
    [Migration("20230515191710_Contract")]
    partial class Contract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("SistemaServitec.Models.AddressModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CEP")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipio")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Residencia")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UF")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("complemento")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Addresss");
                });

            modelBuilder.Entity("SistemaServitec.Models.IdentityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgaoExpedicao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Identitys");
                });

            modelBuilder.Entity("SistemaServitec.Models.LeaseContractModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CEP")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataContrato")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataFinal")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataInicial")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Duracao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DuracaoExtenso")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonLocadorId")
                        .HasMaxLength(255)
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonLocatarioId")
                        .HasMaxLength(255)
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoDuracao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoImovel")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValorExtenso")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonLocadorId");

                    b.HasIndex("PersonLocatarioId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("SistemaServitec.Models.PersonModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataNascimento")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipio")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaisNacionalidade")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UF")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("SistemaServitec.Models.AddressModel", b =>
                {
                    b.HasOne("SistemaServitec.Models.PersonModel", "Person")
                        .WithOne("Endereco")
                        .HasForeignKey("SistemaServitec.Models.AddressModel", "PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SistemaServitec.Models.IdentityModel", b =>
                {
                    b.HasOne("SistemaServitec.Models.PersonModel", "Person")
                        .WithOne("Identidade")
                        .HasForeignKey("SistemaServitec.Models.IdentityModel", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SistemaServitec.Models.LeaseContractModel", b =>
                {
                    b.HasOne("SistemaServitec.Models.PersonModel", "PersonLocador")
                        .WithMany()
                        .HasForeignKey("PersonLocadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaServitec.Models.PersonModel", "PersonLocatario")
                        .WithMany()
                        .HasForeignKey("PersonLocatarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonLocador");

                    b.Navigation("PersonLocatario");
                });

            modelBuilder.Entity("SistemaServitec.Models.PersonModel", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("Identidade");
                });
#pragma warning restore 612, 618
        }
    }
}
